# Generated by Django 2.2.28 on 2025-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0003_auto_20250414_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='membranetopol',
            name='membranetopology_id_old',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='num_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
